name: Lint docs

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Enable corepack
          run: |
            mkdir -p $HOME/bin
            export PATH=$HOME/bin:$PATH
            echo "$HOME/bin" >> $GITHUB_PATH
            corepack enable --install-directory $HOME/bin
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install dependencies
          run: yarn install --immutable
        - name: prettier
          run: yarn lint
